[General]
SwitchDelay=600

[Layout]
; https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-input-locales-for-windows-language-packs?view=windows-11
; English (United States)
TargetLayout=0x04090409

[Options]
CheckInterval=200